In [1]:
import pandas as pd
# import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("spotify_data.csv")

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3441197 entries, 0 to 3441196
Data columns (total 7 columns):
 #   Column      Dtype
---  ------      -----
 0   Position    int64
 1   Track Name  object
 2   Artist      object
 3   Streams     int64
 4   URL         object
 5   Date        object
 6   Region      object
dtypes: int64(2), object(5)
memory usage: 183.8+ MB

In [3]:
#Checking for duplicate rows
data[data.duplicated()]

#Checking for negative streams
(data["Streams"] < 0).any()

#Changing the data type of Date field 
data["Date"] = pd.to_datetime(data["Date"])

### Top 20 Most Streamed Artist from the Daily World Rankings of Spotify Philippines in 2017

In [24]:
df = data[data["Region"] == 'ph']
df[df["Date"].dt.year == 2017].groupby(["Artist"], as_index=False).agg({"Streams": "sum"}).sort_values("Streams", ascending=False).head(20)

               Artist    Streams
108        Ed Sheeran  196795860
339  The Chainsmokers  127464621
55         Bruno Mars  112082581
173        Jonas Blue   66363060
238          Maroon 5   63474421
256  Moira Dela Torre   61400593
197              LANY   56323962
153      James Arthur   52239272
70       Charlie Puth   51867753
138  Hailee Steinfeld   51656510
78       Clean Bandit   48378089
240     Martin Garrix   47708866
319  Silent Sanctuary   45985493
308         Sam Smith   45579042
371              ZAYN   42572916
218        Luis Fonsi   40894853
200              Lauv   40184605
84          DJ Khaled   39546629
192            Khalid   39090055
211        Little Mix   35628489

### Top 20 Songs that Appeared the Most in the Daily World Rankings of Spotify Philippines

In [16]:
data[data["Region"] == "ph"]["Track Name"].value_counts().sort_values(ascending=False).head(20)

Hiling                                                   387
Your Love - Dolce Amore Teleserye Theme                  371
Sila                                                     371
Closer                                                   371
So Sick                                                  371
Say You Won't Let Go                                     371
Tell Me Where It Hurts                                   371
Starving                                                 371
Take A Bow - Main                                        371
The Scientist                                            371
Pasensya Ka Na                                           371
Migraine                                                 371
Versace On The Floor                                     371
It's Gotta Be You                                        371
Malaya (Camp Sawi Original Motion Picture Soundtrack)    371
Sa'yo                                                    371
Tadhana                                                  371
Photograph                                               371
Hanggang Kailan                                          371
That's What I Like                                       371
Name: Track Name, dtype: int64

### Top 20 Artist with the Most Number of Songs in Daily Rankings of Spotify Philippines

In [17]:
data[data["Region"] == "ph"][["Artist", "Track Name"]].groupby(["Artist"]).count().sort_values("Track Name", ascending=False).head(20).rename(columns={"Track Name": "Count"})

                  Count
Artist
Ed Sheeran         3480
The Chainsmokers   1912
Bruno Mars         1483
Silent Sanctuary   1256
LANY               1249
Maroon 5           1211
Charlie Puth       1042
Jonas Blue          965
Ariana Grande       939
Little Mix          881
The Script          871
Jason Mraz          840
Sam Smith           764
Coldplay            755
Hailee Steinfeld    744
South Border        739
Freestyle           737
Moira Dela Torre    733
Martin Garrix       715
Shawn Mendes        696

### Top 20 Artist with Most Number of Unique Songs in Daily Rankings of Spotify Philippines

In [26]:
df = data[data["Region"] == "ph"][["Artist", "Track Name"]].groupby("Artist").nunique().sort_values("Track Name", ascending=False).head(20)
df.rename(columns={"Track Name": "Unique_Songs_Count"}, inplace=True)
df

                  Unique_Songs_Count
Artist
Linkin Park                       32
Coldplay                          29
Taylor Swift                      27
Ed Sheeran                        27
Sam Smith                         21
The Chainsmokers                  18
LANY                              16
Maroon 5                          13
BTS                               13
Kendrick Lamar                    12
Bruno Mars                        12
James Reid                        10
Drake                             10
Katy Perry                         7
Ariana Grande                      7
Calvin Harris                      7
Camila Cabello                     7
Charlie Puth                       7
Adele                              7
Paramore                           7

### Top 20 Most Streamed Songs in the Philippines 2017

In [25]:
df2 = data[data["Date"].dt.year == 2017]
df3 = df2[df2["Region"] == 'ph'].groupby(["Artist", "Track Name"], as_index=False).agg({"Streams": "sum"}).sort_values(["Streams"], ascending=False).head(20)
df3

,Artist,Track Name,Streams
267,Ed Sheeran,Shape of You,57245668
358,James Arthur,Say You Won't Let Go,47481000
105,Bruno Mars,Versace On The Floor,43845108
102,Bruno Mars,That's What I Like,41557904
823,The Chainsmokers,Something Just Like This,38343683
546,Luis Fonsi,Despacito - Remix,34257558
262,Ed Sheeran,Perfect,34142751
191,DJ Khaled,I'm the One,31753339
623,Moira Dela Torre,Malaya (Camp Sawi Original Motion Picture Soun...,31070818
879,ZAYN,I Don’t Wanna Live Forever (Fifty Shades Darke...,28258741
347,Inigo Pascual,Dahil Sa'Yo,27733673
396,Jonas Blue,Mama,26810736
325,Hailee Steinfeld,Starving,26232631
35,Andy Grammer,Fresh Eyes,26058512
154,Clean Bandit,Symphony (feat. Zara Larsson),26022718
812,The Chainsmokers,Closer,25864742
449,Khalid,Young Dumb & Broke,25861189
479,Lauv,I Like Me Better,25349681
489,Liam Payne,Strip That Down,25234131
136,Charlie Puth,Attention,24894603